String HTML(uint8_t r, uint8_t g, uint8_t b, String mode) {
    
    String ptr += "<!DOCTYPE html>";
        ptr += "<!DOCTYPE html>";
        ptr += "<html lang=\"en\">";
        ptr += "<head>";
        ptr += "<meta charset=\"UTF-8\">";
        ptr += "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">";
        ptr += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
        ptr += "<!-- Bootstrap CSS -->";
        ptr += "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">";
        ptr += "<!-- JavaScript Bundle with Popper -->";
        ptr += "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>";
        ptr += "<!-- Color picker -->";
        ptr += "<script src=\"https://cdn.jsdelivr.net/npm/@jaames/iro\"></script>";
        ptr += "<title>SmartClock</title>";
        ptr += "</head>";
        ptr += "<body class=\"bg-secondary text-white\">";
        ptr += "<div class=\"container\">";
        ptr += "<div class=\"row justify-content-center\">";
        ptr += "<div class=\"col-sm\"></div>";
        ptr += "<div class=\"col-sm\">";
        ptr += "<h1 class=\"text-center\">Smart Clock</h1>";
        ptr += "<br>";
        ptr += "<div class=\"wheel mx-auto\" id=\"colorWheelDemo\"></div>";
        ptr += "</div>";
        ptr += "<div class=\"col-sm\"></div>";
        ptr += "</div>";
        ptr += "<br>";
        ptr += "<div class=\"row justify-content-center\">";
        ptr += "<div class=\"col-sm\"></div>";
        ptr += "<div class=\"col-sm text-center\">";
        ptr += "<div class=\"dropdown\">";
        ptr += "<button class=\"btn btn-primary dropdown-toggle\" type=\"button\" id=\"modeSelection\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">";
        ptr += "Select the mode";
        ptr += "</button>";
        ptr += "<ul class=\"dropdown-menu\" aria-labelledby=\"modeSelection\">";
        ptr += "<li><a class=\"dropdown-item\" href=\"/clock\">Clock</a></li>";
        ptr += "<li><a class=\"dropdown-item\" href=\"/timer\">Timer</a></li>";
        ptr += "<li><a class=\"dropdown-item\" href=\"/waves\">Waves</a></li>";
        ptr += "</ul>";
        ptr += "</div>";
        ptr += "</div>";
        ptr += "<div class=\"col-sm\"></div>";
        ptr += "</div>";
        ptr += "</div>";
        ptr += "<script>";
        ptr += "var colorPicker = new iro.ColorPicker(\"#colorWheelDemo\", {";
        ptr += "// Set the size of the color picker";
        ptr += "width: 320,";
        ptr += "// Set the initial color to pure red";
        ptr += "color: {r: " + r + ", g: " + g + ", b:" + b + "},";
        ptr += "borderWidth: 1,";
        ptr += "borderColor: \"#fff\",";
        ptr += "});";
        ptr += "function updateColor(color) {";
        ptr += "let xhr = new XMLHttpRequest();";
        ptr += "xhr.open(\"POST\", \"/updateColor\");";
        ptr += "xhr.setRequestHeader(\"Accept\", \"application/json\");";
        ptr += "xhr.setRequestHeader(\"Content-Type\", \"application/json\");";
        ptr += "xhr.onreadystatechange = function () {";
        ptr += "if (xhr.readyState === 4) {";
        ptr += "console.log(xhr.status);";
        ptr += "console.log(xhr.responseText);";
        ptr += "}};";
        ptr += "let data = JSON.stringify(color.rgb)";
        ptr += "xhr.send(data);";
        ptr += "}";
        ptr += "// Start listening to the color change event";
        ptr += "colorPicker.on(\"color:change\", updateColor);";
        ptr += "</script>";
        ptr += "</body>";
        ptr += "</html>";

}